services:
  kotha-grpc-server:
    build: .
    ports:
      - '$PORT:$PORT'
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
    command: bun run start
    container_name: kotha-server
    restart: always
    depends_on:
      - db
    environment:
      NODE_ENV: development

  db:
    image: postgres:16
    container_name: kotha-postgres
    restart: always
    environment:
      POSTGRES_USER: '$DB_USER'
      POSTGRES_PASSWORD: '$DB_PASS'
      POSTGRES_DB: '$DB_NAME'
    ports:
      - '$DB_PORT:$DB_PORT'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
