name: Infra CDK

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: 'The environment to build for'
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: true
        description: 'The environment to build for'

permissions:
  contents: read
  id-token: write # for OIDC

jobs:
  cdk-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout infra
        uses: actions/checkout@v3

      - name: Setup Node.js & CDK
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install infra dependencies
        working-directory: server/infra
        run: npm install

      - name: Verify CDK version
        working-directory: server/infra
        run: npx cdk --version

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::287641434880:role/KothaGitHubCiCdRole
          aws-region: us-west-2

      - name: Synthesize CDK template
        working-directory: server/infra
        run: npx cdk synth

      - name: Show CDK diff
        working-directory: server/infra
        run: npx cdk diff

      - name: Deploy to AWS
        working-directory: server/infra
        env:
          AUTH0_DOMAIN: '${{ secrets.VITE_AUTH0_DOMAIN }}'
          AUTH0_AUDIENCE: '${{ secrets.VITE_AUTH0_AUDIENCE }}'
          AUTH0_CLIENT_ID: '${{ secrets.VITE_AUTH0_CLIENT_ID }}'
        run: npx cdk deploy "Kotha-${{ vars.AWS_STAGE }}/*" --require-approval never
